### ISSUE TITLE
error: No keys match the given fingerprint, when using keybase CLI

### ISSUE THREAD

**Issue by linuxjuggler** [keybase/keybase-issues#1656] opened 2015-07-05 19:42 UTC
am not sure what is the issue here, but every time I execute `keybase` I got the same error
```
error: No keys match the given fingerprint
```
any idea what is the issue here ?

http://keybase.io/zaher

**Comment by dtiersch** [comment] 2015-07-05 21:10
I guess you don't have the key in your local keyring. Try `keybase pull`.

If this doesn't help please add `-d` to your command and post the debug output here so that we can see where the error may be. (The debug output should be sanitized so no private data is being printed using it)

**Comment by linuxjuggler** [comment] 2015-07-05 21:24
all the commands do the same error message, I have imported my private key to PGP but still nothing any way here is the debug 
```
debug: + opening config file: /Users/zaher/.config/keybase/config.json
debug: ++ loading config file /Users/zaher/.config/keybase/config.json
debug: -- loaded config file -> {"user":{"email":"z@zah.me","name":"zaher","salt":"REMOVED","id":"REMOVED"}}
debug: - opened config file; found=true
debug: + testing GPG command-line client <default: gpg2 or gpg>
debug: | using GPG command: gpg
debug: - tested GPG command-line client -> null
debug: Setting GPG_TTY=/dev/ttys000
debug: + Load proxy CAs
debug: - Loaded proxy CAs
debug: + startup message
debug: | CLI version: 0.8.6
debug: | Platform info: {"versions":{"http_parser":"2.3","node":"0.12.4","v8":"3.28.71.19","uv":"1.5.0","zlib":"1.2.8","modules":"14","openssl":"1.0.1m"},"arch":"x64","platform":"darwin","features":{"debug":false,"uv":true,"ipv6":true,"tls_npn":true,"tls_sni":true,"tls_ocsp":true,"tls":true}}
debug: | Version info: ["keybase (keybase.io CLI) v0.8.6","- node.js v0.12.4","- gpg (GnuPG/MacGPG2) 2.0.27","- libgcrypt 1.6.3","Identifies as: 'keybase.io node.js client v0.8.6 darwin'"]
debug: - startup message
debug: + opening database file: /Users/zaher/.local/share/keybase/keybase.idb
debug: ++ DB::_init_db
debug: -- DB::_init_db -> 0
debug: - DB opened
debug: + session::load
debug: ++ opening config file: /Users/zaher/.cache/keybase/session.json
debug: +++ loading config file /Users/zaher/.cache/keybase/session.json
debug: --- loaded config file -> <redacted>
debug: -- opened config file; found=true
debug: - session::load
debug: + session::check
debug: | calling to sesscheck
debug: ++ request to sesscheck (https://api.keybase.io:443/_/api/1.0/sesscheck.json) (cookie=true)
debug: || Adding a custom CA for host api.keybase.io when tls=true
debug: -- request to sesscheck -> HttpError: Got reply 504
debug: - session::check
error: Got reply 504
```

**Comment by maxtaco** [comment] 2015-07-05 21:24
Let me take a look.

**Comment by maxtaco** [comment] 2015-07-05 21:32
@oconnor663 the issue is that @linuxjuggler at some point change his public key, and it doesn't look like his client is loading the previous key.

**Comment by linuxjuggler** [comment] 2015-07-05 21:33
@maxtaco any idea how to fix that ? I guess the Web Portal should works fine, as I deleted the public key and regenerate one from the Web so it should be replaced right ?

**Comment by maxtaco** [comment] 2015-07-05 21:34
it's our bug, we'll fix it, but might not get to it today.  I'll let you know.  Thanks for the report.

**Comment by linuxjuggler** [comment] 2015-07-05 21:34
@maxtaco no problem just ping me here or on twitter @zaherg .

thanks

**Comment by maxtaco** [comment] 2015-07-05 22:02
So @oconnor663, here's the issue.  The first sig in @linuxjuggler's sigchain is signed with the subkey whose key ID `4C74440DFBF902F7`, which is a subkey of key fingerprint `da4cb664731cfe967a9bbcbd0901ad0153f1b4cd` AKA kid `0101e83b4a8fb5e6144483f835b13e9b6b61ea6ecd60d9084dab1dd2d8d79582e70b0a`.  

The issue is that the public key has been uploaded multiple times with different subkeys.  So the key upload whose id is `883855fc34c3abe08dde6b9d57ea1e11` has the subkey in question; others do not.

Hmf.  Not totally sure how we fix this..  We might have to suck in all public bundles and try them all.  Maybe in reverse chronological order...

**Comment by linuxjuggler** [comment] 2015-07-05 22:10
@maxtaco I didnt upload the public key many time ( I did tried to upload my public key but for some reasons the uploader refuse it ) so that I generate one via the portal and use it.

if there is anything I can help with let me know.

**Comment by maxtaco** [comment] 2015-07-05 23:35
Should work in v0.8.8

**Comment by linuxjuggler** [comment] 2015-07-05 23:43
great, worked like a charm , thanks @maxtaco

**Comment by R3s1stanc3** [comment] 2015-07-15 14:23
I've got the same error for every cli command, I try to execute.
$ keybase -v
0.8.9
On Arch Linux (installed from the AUR)
$ keybase -d login
debug: + opening config file: /home/me/.config/keybase/config.json
debug: ++ loading config file /home/me/.config/keybase/config.json
debug: -- loaded config file -> {"user":{"id":"64a172d67883dd8dbc172bcd0535c419","name":"r3s1stanc3"}}
debug: - opened config file; found=true
debug: + testing GPG command-line client <default: gpg2 or gpg>
debug: | using GPG command: gpg2
debug: - tested GPG command-line client -> null
debug: Setting GPG_TTY=/dev/pts/0
debug: + Load proxy CAs
debug: - Loaded proxy CAs
debug: + startup message
debug: | CLI version: 0.8.9
debug: | Platform info: {"versions":{"http_parser":"2.3","node":"0.12.7","v8":"3.28.71.19","uv":"1.6.1","zlib":"1.2.8","modules":"14","openssl":"1.0.2d"},"arch":"x64","platform":"linux","features":{"debug":false,"uv":true,"ipv6":true,"tls_npn":true,"tls_sni":true,"tls_ocsp":true,"tls":true}}
debug: | Version info: ["keybase (keybase.io CLI) v0.8.9","- node.js v0.12.7","- gpg (GnuPG) 2.1.6","- libgcrypt 1.7.0-beta165","Identifies as: 'keybase.io node.js client v0.8.9 linux'"]
debug: - startup message
debug: + opening database file: /home/me/.local/share/keybase/keybase.idb
debug: ++ DB::_init_db
debug: -- DB::_init_db -> 0
debug: - DB opened
debug: + session::load
debug: ++ opening config file: /home/me/.cache/keybase/session.json
debug: +++ loading config file /home/me/.cache/keybase/session.json
debug: --- loaded config file -> <redacted>
debug: -- opened config file; found=true
debug: - session::load
debug: + session::check
debug: | calling to sesscheck
debug: ++ request to sesscheck (https://api.keybase.io:443/_/api/1.0/sesscheck.json) (cookie=true)
debug: || Adding a custom CA for host api.keybase.io when tls=true
debug: -- request to sesscheck -> null
debug: - session::check
debug: + KeyPull::run
debug: ++ KeyPull::load_user
debug: +++ r3s1stanc3: load user
debug: ++++ r3s1stanc3: load user from local storage
debug: +++++ load sig chain from local storage
debug: ||||| No payload hash tail pointer found
debug: ----- loaded sig chain from local storage
debug: ---- r3s1stanc3: loaded user from local storage -> null / [object Object]
debug: ||| Checking session since we're loading User as self (and need secret key)
debug: ++++ session::load_and_check
debug: +++++ session::check
debug: ||||| calling to sesscheck
debug: ++++++ request to sesscheck (https://api.keybase.io:443/_/api/1.0/sesscheck.json) (cookie=true)
debug: |||||| Adding a custom CA for host api.keybase.io when tls=true
debug: ------ request to sesscheck -> null
debug: ----- session::check
debug: ---- session::load_and_check -> true
debug: ++++ r3s1stanc3: load user from server
debug: +++++ merkle find_and_verify: uid undefined, username r3s1stanc3
debug: ++++++ request to merkle/path (https://api.keybase.io:443/_/api/1.0/merkle/path.json?uid=&username=r3s1stanc3) (cookie=true)
debug: |||||| Adding a custom CA for host api.keybase.io when tls=true
debug: ------ request to merkle/path -> null
debug: ++++++ merkle get_merkle_pgp_key
debug: |||||| Call to gpg2: { args: [ '-k', '--with-fingerprint', '--with-colons' ],
debug:   quiet: true,
debug:   no_options: true }
debug: |||||| merkle key already found in keyring
debug: ------ merkle get_merkle_pgp_key
debug: ||||| Load key /2A32340CEC8C9492 from master keyring (secret=undefined)
debug: ||||| Call to gpg2: { args: 
debug:    [ '--export',
debug:      '--export-options',
debug:      'export-local-sigs',
debug:      '-a',
debug:      '2A32340CEC8C9492' ] }
debug: ++++++ lookup UID
debug: +++++++ read_uids_from_keys 03E146CDAF8136680AD566912A32340CEC8C9492
debug: ||||||| Call to gpg2: { args: 
debug:    [ '-k',
debug:      '--with-fingerprint',
debug:      '--with-colons',
debug:      '03E146CDAF8136680AD566912A32340CEC8C9492' ],
debug:   quiet: true,
debug:   no_options: true }
debug: ||||||| got: [{"username":"Keybase.io Merkle Signing","comment":"v1","email":"merkle@keybase.io"}]
debug: ------- read_uids_from_key -> null
debug:  - Map 2A32340CEC8C9492 -> [object Object] via gpg
debug: ------ looked up UID
debug: ++++++ Rollback check
debug: |||||| DB put value kv:e2:d7c76dad1775bda91cf4a51749c8f52234c868bc576bdea0f9e41e065350630bbaab37b23b69f03815acdb99f239857a90fb6df2df6cb1582540e5bafeceb9d3
debug: |||||| DB put lookup: lo:5:latest -> 78b67fca2da77d178ca21f4da9d2497dab37d3f347aad2a40df3bf91f34a16be
debug: ------ Rollback check
debug: ++++++ request to user/lookup (https://api.keybase.io:443/_/api/1.0/user/lookup.json?username=r3s1stanc3) (cookie=true)
debug: |||||| Adding a custom CA for host api.keybase.io when tls=true
debug: ------ request to user/lookup -> null
debug: ----- r3s1stanc3: loaded user from server
debug: +++++ updating local user w/ remote
debug: ++++++ update sig chain; remote_seqno=16
debug: |||||| sigchain update: 16 vs. null
debug: +++++++ sigchain::_update
debug: ++++++++ request to sig/get (https://api.keybase.io:443/_/api/1.0/sig/get.json?uid=64a172d67883dd8dbc172bcd0535c419&low=1) (cookie=true)
debug: |||||||| Adding a custom CA for host api.keybase.io when tls=true
debug: -------- request to sig/get -> null
debug: ||||||| found 16 new signatures
debug: ------- sigchain::_update
debug: |||||| update sig_chain last link to {"seqno":16,"payload_hash":"d84ca91bf1e6efc15bcf968472d7c834a5da4732c624e0247585960e6a7d9dd6","sig_id":"cdecebcb2a3b8b2a21aa3ad331c1e9362c427089064566771fee4cbdbcddd43b0f"}
debug: ------ updated sig chain
debug: ----- finished update
debug: +++++ r3s1stanc3: verifying signatures
debug: ++++++ r3s1stanc3: verifying sig
error: No keys match the given fingerprint

**Comment by maxtaco** [comment] 2015-07-15 14:26
It's likely our bug, we'll take a look today.  Thanks for the feedback.

**Comment by oconnor663** [comment] 2015-07-15 15:05
Yep, we found it. Looks like it's an issue with how we handle superseded keys (ones reuploaded with e.g. new subkeys) differently from revoked-and-reuploaded keys. Should be a pretty easy fix. Will update you here when it's live, @R3s1stanc3.

**Comment by oconnor663** [comment] 2015-07-15 18:30
Alright @R3s1stanc3, it should be fixed now. No need to update your client, just try those commands again. Let us know if anything keeps breaking for you.

**Closed by oconnor663** 2015-07-15 18:30 UTC
