### ISSUE TITLE
Keep seeing "bad e-mail" when trying to invite friends

### ISSUE THREAD

**Issue by msrmichaelson** [keybase/keybase-issues#1300] opened 2015-01-06 13:33 UTC
Hello,

Keybase very kindly gave me 4 invites to keybase alpha for friends. I've chosen wisely, obviously- but now I can't seem to actually invite them! When I enter a basic gmail address, including trying it in the googlemail format, it just says "bad e-mail address specified". The address is definitely valid. 

So...what's up?

**Comment by malgorithms** [comment] 2015-01-06 13:54
hmm, any chance you can share the address you're trying to invite?  I can't reproduce this prob.

also:

  - what browser are you using?
  - are you seeing anything in the JS console?

thanks / sorry!

**Comment by msrmichaelson** [comment] 2015-01-06 14:40
Hi Chris,

Firstly, thanks for being so responsive!

So it turns out, when I type the e-mail address in, it's fine. But if I
copy and paste it, it doesn't like it. I'm using google chrome, if that
helps.

All the best,

Ruth

On 6 January 2015 at 13:54, Chris Coyne <notifications@github.com> wrote:

> hmm, any chance you can share the address you're trying to invite? I can't
> reproduce this prob.
>
> also:
>
>    - what browser are you using?
>    - are you seeing anything in the JS console?
>
> thanks / sorry!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/keybase/keybase-issues/issues/1300#issuecomment-68867414>
> .
>



-- 
Ruth Michaelson

UK:   +44 7950 218594
EGY: +20 102 893 8550
LEB: + 961 76 993 843

Twitter: @_Ms_R
PGP: 0x000C3381
Skype: ruth.michaelson

https://www.frontlinefreelance.org/

**Comment by malgorithms** [comment] 2015-01-06 15:03
oh that's interesting. I'm going to make an educated guess that you're picking up whitespace in your copy and I have a bug that I'm not stripping leading/trailing whitespace...I just confirmed I'm not stripping it there.  Closing this out and fixing it in the next hour.

**Closed by malgorithms** 2015-01-06 15:03 UTC
