### ISSUE TITLE
Cannot "upload" a new key

### ISSUE THREAD

**Issue by birdmeister** [keybase/keybase-issues#1779] opened 2015-09-20 10:05 UTC
The new key was generated by the Keybase website (not via the command line tool).

<img width="1334" alt="screen shot 2015-09-20 at 12 00 06" src="https://cloud.githubusercontent.com/assets/761601/9980204/cece3548-5f8f-11e5-9c3c-63d13c6e25de.png">

**Comment by zQueal** [comment] 2015-09-20 15:58
Interesting error!

Try removing your private key from Keybase before you try to generate a new key pair.

![image](http://i.imgur.com/eC3My4v.png)

**Comment by birdmeister** [comment] 2015-09-20 16:15
I can't delete my private key from keybase through the menu. I've tried to revoke it from the command line but that does not work either. Maybe I should delete some files, but not sure which ones...

**Comment by maxtaco** [comment] 2015-09-20 16:16
Our bug. We will look into it on Monday.

**Comment by maxtaco** [comment] 2015-09-21 00:38
Related to #1778

**Comment by malgorithms** [comment] 2015-09-21 14:09
yeah, I'm on this. @birdmeister  - did you (1) bring in your own key from the outside, then (2) skip the step where you prove you have the private key (by signing a statement accepting the public key into your account)? Then (3) try to switch to generating one in the browser?

 I'm looking for steps to reproduce this.

**Comment by malgorithms** [comment] 2015-09-21 14:50
@birdmeister  - can you try to visit the site now and see if it gives you more sensible options? I think I have fixed this, assuming my above explanation is correct.

**Comment by birdmeister** [comment] 2015-09-21 19:39
@malgorithms That is indeed the correct flow. On the site, I now see 2 options:
1- Sign my public key to prove it's mine
2- Delete this key and start over [new]

Shall I try out the 2nd option?

**Comment by malgorithms** [comment] 2015-09-21 19:48
excellent.

You can try whichever you want (especially since your account is empty)...if you have the private key in GPG that goes to whatever public key you uploaded, you can do option 1. It'll give you the GPG commands to sign your key. If you don't, option 2 is good.

Either way!

Closing...but please reopen if you hit a snag.

**Closed by malgorithms** 2015-09-21 19:48 UTC

**Comment by birdmeister** [comment] 2015-09-21 19:52
W00t! It now works. Tx
