### ISSUE TITLE
OSX(10.11.5) keybase(GUI) starts when login

### ISSUE THREAD

**Issue by D0zingcat** [keybase/keybase-issues#2477] opened 2016-08-11 09:03 UTC
Could anybody tell me how to turn off the autostart configuration on OSX?

It's quite annoying the keybase app shows up when the system starts!

**Comment by fzzr-** [comment] 2016-08-12 17:28
Simply unload & remove three files:
```
~/Library/LaunchAgents/keybase.kbfs.plist
~/Library/LaunchAgents/keybase.service.plist
~/Library/LaunchAgents/keybase.updater.plist
```

Run this shell command:
```bash
cd ~/Library/LaunchAgents; launchctl unload keybase.*; rm ./keybase.*
```

**Comment by fzzr-** [comment] 2016-08-12 17:49
But I don't know what doing next tool:
```
/Library/PrivilegedHelperTools/keybase.Helper
```

**Comment by MattiSG** [comment] 2016-09-30 13:35
Duplicate of #2448 (#2448 is better phrased).

**Closed** 2016-10-01 15:51 UTC
