### ISSUE TITLE
My public key block won't pop up

### ISSUE THREAD

**Issue by CryptoAmanda** [keybase/keybase-issues#1864] opened 2015-11-19 21:29 UTC
Hi, Keybase! Really enjoy your service. My account is keybase.io/cryptoamanda, and when I visit others' pages, I seem to be able to view their public key block by clicking on their fingerprint. But when I try to click on my own fingerprint, nothing happens. I have to sign in in order for it to show.

Is this normal? Or is there a problem on my end, or on your end?

Thanks,
Amanda
@TheDailyDecrypt

**Comment by zQueal** [comment] 2015-11-19 21:47
Hi Amanda,

This does seem to be a bug, as I'm pretty sure it's not by design. While logged in, your public key is displayed as intended, but not when logged out. Additionally, you always have access, logged in or logged out, to your hosted public key here: `https://keybase.io/cryptoamanda/key.asc`

I don't speak for Keybase, but this doesn't like normal behavior.

**Comment by malgorithms** [comment] 2015-11-20 01:08
Yeah, hmm, a bug! I can't reproduce this. Some q's:

1. what browser/OS are you using?
2. do you see any JS errors in your console?

**Comment by zQueal** [comment] 2015-11-20 01:37
POST https://keybase.io/_/modal/key/show_pgp_public 403 (Forbidden)

Chrome 46.0.2490.86m.

**Comment by CryptoAmanda** [comment] 2015-11-20 18:52
Well, it seems to be working now. Not sure if things are different on my end, or what. I do use a Profile Spoofing plugin, so maybe it works for some spoofed browsers and not others? Thanks for the feedback, fellas. I suspect that it's the profile spoofer, which would explain why I can view my key sometimes, but not others. Cheers!

**Comment by zQueal** [comment] 2015-11-20 20:39
I can confirm that this error is still present for me:

> Failed to load resource: the server responded with a status of 403 (Forbidden)

I suspect it has more to do with server-side than anything. I have no such plugin installed in chrome and I'm getting the same errors you were--however, only when a guest and logged out.

**Comment by malgorithms** [comment] 2015-11-20 21:21
ohhhhh, that's the prob. It's breaking when logged out.  

I think I broke something while refactoring. Looking into this...

**Comment by malgorithms** [comment] 2015-11-20 21:30
ok, this should be fixed now. thanks

**Closed by malgorithms** 2015-11-20 21:30 UTC
