### ISSUE TITLE
Error 1002 when trying to track a user's key

### ISSUE THREAD

**Issue by grant-olson** [keybase/keybase-issues#1770] opened 2015-09-17 16:03 UTC
I get the following error when trying to track another user's gpg key:

```
Error in your post
-------------------

Code: 1002
Name: SIG_CANNOT_VERIFY
Description: bad signature: Can't find a key for fe45e55da18a54d6: No keys match the given key IDs
```
I do have that key in my keyring:

```
master-blaster:www.grant-olson.net grant$ gpg --list-secret-keys fe45e55da18a54d6
/Users/grant/.gnupg/secring.gpg
-------------------------------
sec#  2048R/E3B5806F 2010-01-11 [expires: 2015-01-03]
uid                  Grant T. Olson (Grant - home email) <olsongt@verizon.net>
uid                  Grant T. Olson (Personal email) <kgo@grant-olson.net>
uid                  Grant T. Olson (pikimal) <grant@pikimal.com>
ssb   2048R/6A8F7CF6 2010-01-11
ssb   2048R/A18A54D6 2010-03-01
ssb   2048R/D53982CE 2010-08-31
```

I do have a separate SIGNING key that is different than my CERTIFICATION key, and the certification private key is not on this system, but I assume keybase just does a normal signature and not a certification for the WoT here. Let me know if I'm wrong.

**Comment by Sidnicious** [comment] 2015-09-17 17:49
Thanks for all the details. I was able to recreate this, and it looks like a bug on our end. We're investigating — I'll keep you posted!

**Comment by Sidnicious** [comment] 2015-09-17 19:27
@grant-olson Actually, I take that back. When I paste your public key into gpg, I get this output:

```
pub  2048R/E3B5806F 2010-01-11 Grant T. Olson (Personal email) <kgo@grant-olson.net>
uid                            Grant T. Olson (pikimal) <grant@pikimal.com>
uid                            Grant T Olson <grant@webkite.com>
uid                            MyBitSafe Support <support@mybitsafe.com>
uid                            Grant T. Olson (Grant - home email) <olsongt@verizon.net>
sub  2048R/A18A54D6 2010-03-01 [expires: 2015-01-04]
sub  2048R/D53982CE 2010-08-31 [expires: 2015-01-04]
sub  2048R/6A8F7CF6 2010-01-11 [expires: 2015-01-04]
```

The error message from us should be better, but I believe the issue is that the keys have expired. Try to extend their expiration dates and re-upload your key, then try tracking someone again. Let me know how it goes!

**Comment by grant-olson** [comment] 2015-09-17 19:32
No I rotate the expiration yearly so that people need to update their keyrings. the keys on pool.sks-keyserver.net have an expiration of 12-31-2015.

```uid Grant T. Olson (Personal email) <kgo@grant-olson.net>
sig  sig3  E3B5806F 2010-01-11 __________ __________ [selfsig]
sig  sig3  E3B5806F 2010-01-23 __________ __________ [selfsig]
....
sig  sig3  E3B5806F 2014-01-03 __________ 2015-01-03 [selfsig]
sig  sig3  E3B5806F 2014-01-04 __________ 2015-01-04 [selfsig]
sig  sig3  E3B5806F 2014-12-29 __________ 2015-12-31 [selfsig]
```

Last one is the latest expiration sig.

**Comment by grant-olson** [comment] 2015-09-17 19:35
Are you using gpg to maintain your local keyring? You probably need a nightly job to run `gpg --refresh-keys` Those changes have been out in the wild for 9 months now.

**Comment by grant-olson** [comment] 2015-09-17 19:50
Oh are you guys just using the keys we upload and not syncing with the keyserver network? I guess I can update my key there but you probably should be checking the network to get revocations automatically.

**Comment by grant-olson** [comment] 2015-09-17 19:55
After updating my key on keybase.io I now get this error.

```
Error in your post
-------------------

Code: 901
Name: KEY_NOT_FOUND
Description: signing_kid 01014be82149757c17cfdcc2b2ac6d6206edb06c75d4239334846638c918850303700a not found
master-blaster:adwords grant$ 
``

**Comment by Sidnicious** [comment] 2015-09-18 18:12
See my comment on the other bug re. pulling updates from keyservers, and I'm investigating this new error now.

**Comment by Sidnicious** [comment] 2015-09-18 19:58
This was a server side issue and should be fixed now. Give it another shot!

**Closed by Sidnicious** 2015-09-18 19:58 UTC
