### ISSUE TITLE
keybase, kbfsfuse, keybase-redirector continue to run after client exit - unacceptable

### ISSUE THREAD

**Issue by hook-s3c** [keybase/keybase-issues#3242] opened 2018-05-19 13:04 UTC
- check `ps`, these processes aren't running
- open the client, processes start
- close the client, processes hang around until I `kill`

- ports are still open `netstat -tupln`

Unacceptable - what's going on here?

**Comment by strib** [comment] 2018-05-19 15:16
You haven't said what platform you're on.  If you're on Linux, client exit doesn't do anything, we haven't yet built a mechanism to stop Keybase on Linux.  You can manually execute the contents of the `kill_all` function in `which run_keybase` if you want to stop it.

**Comment by simbalion** [comment] 2018-05-19 15:49
How is it possible that you "haven't yet built a mechanism to stop Keybase on Linux."???

The app can't even be called alpha if it can't be exited.

**Comment by junderw** [comment] 2018-05-21 03:51
Copy pasting this into bashrc and naming it `kill_keybase` helped me.

https://github.com/keybase/client/blob/0fb9afde662171f890dbbf2c1811bf523b81437c/packaging/linux/run_keybase#L101-L133

**Comment by junderw** [comment] 2018-05-21 03:59
just found out I need to use `sudo killall keybase-redirector` to kill the redirector since the process is run by root.

The above now works for me (I modified it slightly)

**Comment by junderw** [comment] 2018-05-21 04:38
suggestion: https://stackoverflow.com/questions/18106749/golang-catch-signals

catch SIGTERM for the keybase process, and before dying, use os.System to find all the processes running (like you do in the killall bash command) and run a SIGTERM kill for each one.

for keybase-redirector since it requires root priveleges to kill... I guess just change the app to not require a root process... or echo a message saying "please kill the root process as root or with sudo killall keybase-redirector" etc.

**Comment by junderw** [comment] 2018-05-21 04:39
imo, "Quit" button on the GUI shouldn't kill anything except the Electron app... I want the kbfs to keep running in the background... but yeah, if I `kill keybase` it would make sense that kbfs is no longer usable.

**Comment by oconnor663** [comment] 2018-05-21 14:57
Stopping Keybase through systemd is the cleanest way to do it:

    systemctl --user stop keybase kbfs keybase.gui

As @strib mentioned, quitting the GUI only quits the GUI, and isn't equivalent to running that command. That's admittedly confusing in some cases, but I don't think the alternative is 100% safe either. Our Linux install base is much more heterogeneous than our users on Mac and Windows; people will install KBFS in headless mode, or maybe configure just `keybase.service` and `kbfs.service` to start on boot. In more...interesting...setups like that, killing the services on GUI exit could be the wrong assumption.

As @junderw mentioned, the root redirector service needs `sudo` to stop it. (It serves symlinks to all users on your system, so it runs as root.) The cleanest way to stop it is to unmount it:

    sudo fusermount -u /keybase

**Comment by kwilczynski** [comment] 2019-03-19 01:23
Hi there everyone! :wave:

For me the issue is more with the UI, as I do not mind the keybase service and support for KBFS to stay running in the background.

For some reason, every time I run UI, then it would create a new process, which seem to never quit and/or be closed. This causes more processes to amass over time every time UI is started.

Additionally, since UI seem to never quit/terminate, the desktop notifications are always delivered, even though there is no actual UI in front of me running. This is something that is a bit undesired.

**Comment by heronhaye** [comment] 2019-03-19 15:11
@kwilczynski If you do `systemctl --user stop keybase.gui`, the UI process will shutdown and you will not get notifications anymore.

**Comment by heronhaye** [comment] 2019-03-19 15:14
>For some reason, every time I run UI, then it would create a new process, which seem to never quit and/or be closed. This causes more processes to amass over time every time UI is started.
This is surprising. Could you show the results of `ps aux | grep Keybase` after you "run the UI" a few times?

---

Also, note that for a while, we've had the `run_keybase -k` option which kills all processes, and the `run_keybase -g` which will start all processes except the gui (so, the service and KBFS). If you do `run_keybase -g` but the gui is already running, it will be shut down.

**Comment by kwilczynski** [comment] 2019-03-20 04:06
Hi @heronhaye just to make sure, I updated to the latest version, and it seems to have fixed the process sprawl as per:

```
 |-+= 02437 kwilczyn /lib/systemd/systemd --user 
 | |-+= 26244 kwilczyn /opt/keybase/Keybase 
 | | |--- 26279 kwilczyn /opt/keybase/Keybase --type=gpu-process --enable-features=SharedArrayBuffer --no-sandbox --gpu-preferences=KAAAAAAAAACAAABAAQAAAAAAAAAAAGAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAA --service-request-channel-token=413201142
 | | \-+- 26248 kwilczyn /opt/keybase/Keybase --type=zygote --no-sandbox 
 | |   |--- 26297 kwilczyn /opt/keybase/Keybase --type=renderer --no-sandbox --enable-features=SharedArrayBuffer --service-pipe-token=6110554257623300095 --lang=en-GB --app-path=/opt/keybase/resources/app --node-integration=true --webview
 | |   \--- 26284 kwilczyn /opt/keybase/Keybase --type=renderer --no-sandbox --enable-features=SharedArrayBuffer --service-pipe-token=5853500225219260331 --lang=en-GB --app-path=/opt/keybase/resources/app --node-integration=true --webview
```

Re: Keybase notifications - thank you for the tip, much appreciated. Albeit, this is not the behaviour I would expect. If every time I need to stop a systemd unit to stop notifications, or run a helper which goes and kills all the processes, then it might be something one could address a potential usability bug. 

The "[principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment)" when approaching a software with an UI would be that... if I close it then all activities pertaining to it would also cease. I never had to stop a background service on Mac OS X when using Keybase to stop UI completely and to stop notifications from being shown (perhaps it was also running there but I have never noticed as it wasn't bugging me with unwanted notifications once I quit the UI).

What do you think?

For the time being I am going to add a small Bash shell wrapper to ensure that once the process exits I also call stop on a systemd unit. :)

**Comment by heronhaye** [comment] 2019-03-20 15:33
There is also the popup when you click the system tray icon. Clicking the hamburger icon at the top right -> "Quit App" will close the UI completely as well.

**Comment by kwilczynski** [comment] 2019-03-20 15:48
@heronhaye that might work, although, I do not have a system tray in my case. :smile:

**Comment by heronhaye** [comment] 2019-03-20 16:21
@kwilczynski do you mean your window manager doesn't support a system tray or you don't see the keybase icon there?

**Comment by kwilczynski** [comment] 2019-03-20 20:51
Hi @heronhaye , apologies, I should have add more details. Yes, I use tiling window manager and it does not have tray area or application icons. But, I also tried different distribution that ships Gnome Shell, and it also, out of the box, didn't have tray area (and failed to install one from the add-on web site due to Gnome 3 being too new of a version). Alas, I think tray or not, it's besides the point. :)

**Comment by heronhaye** [comment] 2019-03-21 20:34
That's fair. In an upcoming UI rework the quit app option will be present on the main screen as well.

**Comment by kwilczynski** [comment] 2019-03-24 01:08
Hi @heronhaye, that's a great news! Thank you so much and sorry for troubles! I really appreciate all the work that goes into Keybase. Can't wait to see new UI! :+1:

**Comment by heronhaye** [comment] 2019-05-08 20:43
Keybase 4.0 has a Quit Keybase button in the main app in the GUI.

![2019-05-08-164233_367x601_scrot](https://user-images.githubusercontent.com/28712558/57407074-5671eb80-71b0-11e9-9713-581f9baa3808.png)

Also, `keybase ctl stop` should work as expected on Linux.

**Closed** 2019-05-08 20:43 UTC
