### ISSUE TITLE
Cannot import private PGP key

### ISSUE THREAD

**Issue by Ketchup901** [keybase/keybase-issues#2698] opened 2016-12-03 17:24 UTC
From the command line it gives the following:  
`$ keybase pgp import -i ~/.gnupg/privkey.asc`  
`▶ ERROR This key is already active. You can't add it twice. (error 923)`

On the website it gives `Error: Unknown signature subpacket: 33`

**Comment by maxtaco** [comment] 2016-12-04 00:37
Dupe of an earlier issue. We're working on it.  It's a new feature GPG rolled out :/

**Comment by maxtaco** [comment] 2016-12-04 00:38
See #2668

**Closed by maxtaco** 2016-12-04 00:38 UTC
