### ISSUE TITLE
The elephant emoji in bio removes everything after it.

### ISSUE THREAD

**Issue by svenluijten** [keybase/keybase-issues#2317] opened 2016-06-27 22:33 UTC
This is such an oddly specific bug, but here we go. Inserting the elephant emoji (🐘) anywhere in your bio clears everything that comes after it. Here's a quick demo:

![keybase-emoji-bug](https://cloud.githubusercontent.com/assets/11269635/16397974/d7ede0fe-3cc7-11e6-9800-4d86f9cbf0b7.gif)

So far this is the only emoji I've encountered this bug with, though I haven't tried them all yet.

**Comment by zQueal** [comment] 2016-06-27 22:42
This is just the coolest bug! It seems to be specifically reproducible exactly as described.

**Comment by strib** [comment] 2016-06-27 22:44
@malgorithms: liberal bias?

**Comment by frantic1048** [comment] 2016-06-28 11:15
Same here, but with rabbit emoji 🐰

**Comment by svenluijten** [comment] 2016-06-28 11:18
@frantic1048 Keybase isn't animal friendly, it seems :stuck_out_tongue:

**Comment by malgorithms** [comment] 2016-06-28 13:29
haha @strib 

It appears it's because we're using `utf8` in MySQL for the bio/profile fields - the following article describes the truncation:

https://mathiasbynens.be/notes/mysql-utf8mb4

hopefully we can get to this soon.

**Comment by malgorithms** [comment] 2016-10-14 14:54
Thanks for your patience everyone...this is finally done:

https://keybase.io/chris

let me know if you see any issues, and if not, we can close this out...

**Comment by svenluijten** [comment] 2016-10-14 15:07
Woo! 🐘

![screenshot](http://i.imgur.com/UJhh1cf.png)

**Comment by malgorithms** [comment] 2016-10-17 14:14
excellent, gonna close this issue....

**Closed by malgorithms** 2016-10-17 14:14 UTC
