### ISSUE TITLE
Unable to log in to keybase via cli client

### ISSUE THREAD

**Issue by jottr** [keybase/keybase-issues#1867] opened 2015-11-20 15:15 UTC
When trying to login via cli I get the following error message, when trying to use my keybase password:

```
$ keybase login
How would you like to sign this install of Keybase?

(1) Use an existing device
(2) Use a paper key
(3) Use my Keybase passphrase
(4) Use GPG
Choose a signing option: 3
Your keybase username: jottr
▶ ERROR no device id set
```
Why does the client expect a device id? Weird. 

Now, let's try to login with GPG:

```
keybase login              
                                                                                                                                                        
How would you like to sign this install of Keybase?

(1) Use an existing device
(2) Use a paper key
(3) Use my Keybase passphrase
(4) Use GPG
Choose a signing option: 4

The keybase CLI needs access to your GPG key to authorize this installation. It will
export your secret key from GPG, and save to keybase's local encrypted keyring. This way,
it can be used in `keybase pgp sign` and `keybase pgp decrypt` going forward.
Would you like to continue? [Y/n] Y
#    Algo   Key Id             Created      UserId
=    ====   ======             =======      ======
1    R      redacted ...
Choose a key: 1
▶ ERROR openpgp: invalid data: user ID self-signature invalid: openpgp: invalid signature: hash tag doesn't match
```

Not sure if this is a problem at my end, or a general problem with either keybase, or the go library you guys use. 

```
keybase account: jottr

$ keybase --version
keybase version 1.0.0-47

$ gpg --version
gpg (GnuPG) 1.4.19
...

```

**Comment by maxtaco** [comment] 2015-11-20 15:18
This is a dupe of #1854.  We're going to launch a workaround soon, though we still don't have any ideas about the deeper issue, since we can't repro it without secret key material. Seems like a bug in Go's PGP libraries.

**Comment by jottr** [comment] 2015-11-20 15:21
Also, if someone tries to encrypt a message to me via web frontend, this happens:
<img width="1045" alt="screen" src="https://cloud.githubusercontent.com/assets/2744198/11303352/ad3fbaee-8fa2-11e5-94ad-d13fb19ae8dd.png">

Also related to above dupe?

**Comment by maxtaco** [comment] 2015-11-20 15:23
Sorry for the craptastic error message.  It's because your encryption subkey has expired:

```
pub  4096R/5C98CBD1  created: 2013-07-03  expires: never       usage: SC  
                     trust: unknown       validity: unknown
sub  4096R/74588152  created: 2013-07-03  expired: 2014-07-03  usage: E   
[ unknown] (1). Jonas Tracht <j@ovvvo.co>
[ unknown] (2)  Jonas Tracht <memetical@gmail.com>
[ unknown] (3)  Jonas Tracht <jottr@keybase.io>
```

**Comment by jottr** [comment] 2015-11-20 15:26
@maxtaco Could you please edit out my name and emails out of above message? I don't want them to show up in google. Thx!

**Closed** 2015-11-20 15:37 UTC
