### ISSUE TITLE
push: PGP key expired at time T1 but we checked for time T2

### ISSUE THREAD

**Issue by rnelson** [keybase/keybase-issues#1776] opened 2015-09-19 13:17 UTC
I'm experiencing an issue similar to #1707, except my key isn't expired:

```
rnelson@boxer ~ $ keybase push --update
error: PGP key 67e8a82dc27ab4973f5d377f33e5c81b04cadcba expired at 1422813521 but we checked for time 1425066354
rnelson@boxer ~ $ keybase version
keybase (keybase.io CLI) v0.8.19
- node.js v0.12.7
- gpg (GnuPG/MacGPG2) 2.0.28
- libgcrypt 1.6.3
Identifies as: 'keybase.io node.js client v0.8.19 darwin'
rnelson@boxer ~ $
```

I have the same problem on this Mac and on a Linux box (keybase 0.8.18, node 0.12.7, GPG 2.0.22, libgcrypt 1.5.3) that has a copy of my ~/.gnupg. Like #1707, `status`, `pull`, `push`, `push --update`, and `track` all cause an expiration error.

The key in question is `04cadcba`:

```
pub   2048R/04CADCBA 2012-01-16 [expires: 2016-02-01]
sub   2048R/9C21896F 2012-01-16 [expires: 2016-02-01]
```

**Comment by rnelson** [comment] 2015-09-19 13:21
Correction: I reread 1707 and it's the same. I set yearly expire dates and update them in advance (in case I were to lose my secret keys/whatever). I'm running version >0.8.14 and experiencing the same problem.

**Comment by maxtaco** [comment] 2015-09-19 13:35
Thanks Ross.  We will take a look on Monday.

**Comment by oconnor663** [comment] 2015-09-21 17:43
I think the problem is that the version of the key most recently uploaded to Keybase is in fact expired, and only your local version of your key has been extended.  When I try to import your key myself, I see:

![image](https://cloud.githubusercontent.com/assets/860932/9999439/6f67a618-6064-11e5-94df-f8a7db836348.png)

You should be able to fix this by exporting the latest version of your key and uploading it on your profile. Would you please try this and let us know how it goes? We've recently moved the control for this; now it's the "edit" link here:

![image](https://cloud.githubusercontent.com/assets/860932/9999470/91f08204-6064-11e5-8e4c-f55ec4f120e0.png)

The other question is why you were able to make any signatures at all with an expired key on your account. It looks like your latest signatures were all made with v0.7.7, which is older than the changes we made to check key expiration properly. So then when you updated your client to v0.8.19 and started running these new checks, your account "became" invalid.

I think we've updated the server side at this point to also check for this sort of problem, but that must also have happened after your signatures were made. @maxtaco, does that sound right to you?

**Comment by rnelson** [comment] 2015-09-21 22:00
User error! That fixed it. Thanks, @oconnor663!

**Comment by qrkourier** [comment] 2015-09-22 00:51
I am still experiencing this same issue after using the 'edit' feature of the web app to import the version of my key which is valid and not expired. 

`# my key is not expired (shown here are creation dates)
$ gpg --list-keys 957C5E46
pub   4096R/957C5E46 2013-11-12
uid                  Kenneth Bingham <w@qrk.us>
uid                  Kenneth Bingham <qrz@kourier.io>
uid                  Kenneth Bingham <kourier@keybase.io>
uid                  keybase.io/kourier <kourier@keybase.io>
sub   4096R/9A62231E 2013-11-12
sub   4096R/7ABF3FDD 2014-01-27

# I'm unable to perform any operation that requires a valid key
$ keybase list-signatures
error: PGP key 5489e13f810564df47fb9841b69403fa957c5e46 expired at 1441064361 but we checked for time 1442878069

# the indicated expiry is definitely in the past
$ date
Mon Sep 21 17:45:29 PDT 2015
$ date -d @1441064361
Mon Aug 31 16:39:21 PDT 2015

# export the public key and past in web app's 'edit' window
$ gpg --armor --export 5489e13f810564df47fb9841b69403fa957c5e46|xclip -sel clip
`

**Comment by oconnor663** [comment] 2015-09-22 02:03
@qrkourier it looks like your key previously had an expiration date (which is passed), but now has no expiration. My guess is that we have a bug in the way we merge key versions. I'm experimenting with it now. (We can't just use the latest key version because the latest version might fail to verify some past signatures. The scheme for dealing with this problem is kind of involved.)

**Comment by qrkourier** [comment] 2015-09-26 15:32
Ah, yes. Re-adding an expiry then pasting the new key in the web app and performing 'keybase pull' allows me to operate normally.

**Comment by oconnor663** [comment] 2015-09-26 16:35
You should be able to go back to your non-expiring key as soon as the PR above is landed. Sorry for the trouble.

**Closed** 2017-02-13 16:37 UTC
