### ISSUE TITLE
Error: Unknown curve OID: 2b060104019755010501

### ISSUE THREAD

**Issue by roberto68** [keybase/keybase-issues#2260] opened 2016-05-25 09:11 UTC
I've created new ECC keys ( not NIST standard ~ not "NSA approved" :D )  it's Curve25519 I'll look it up. Anyway it'd be nice to support at least conjunction of those marked as safe https://safecurves.cr.yp.to/ and those available in the gpg2 via --expert option (so you do not have to specify parameters urself ). anyway here's my public key https://gist.github.com/roberto68/7fda189d40154db0d4732c4972a6e909

And also one's able to reset password only via command line? It's good if it's in the FAQ....

**Comment by maxtaco** [comment] 2016-05-25 21:30
It's in our TODO to support Curve25519 in PGP.  We use it everywhere in Keybase device keys.

**Comment by maxtaco** [comment] 2016-05-25 21:30
Dupe of #1738

**Closed by maxtaco** 2016-05-25 21:30 UTC

**Comment by roberto68** [comment] 2016-05-26 16:57
ok thanks
