### ISSUE TITLE
keybase complains I need to push, but I already pushed

### ISSUE THREAD

**Issue by SyntaxPolice** [keybase/keybase-issues#1730] opened 2015-08-12 19:14 UTC
warn: You have not proven ownership of your key. Run `keybase push --update`.
error: You already have a key registered; either revoke or run `keybase push --update`

**Comment by maxtaco** [comment] 2015-08-12 20:03
Try logout and login?

**Comment by SyntaxPolice** [comment] 2015-08-13 00:50
Unfortunately, logging off & logging back in doesn't seem to help.

**Comment by maxtaco** [comment] 2015-08-13 00:50
Ok, this is likely a new regression, since I believe this feature used to work.  cc: @oconnor663

**Comment by SyntaxPolice** [comment] 2015-08-13 00:52
Yes, I'm new.

**Comment by maxtaco** [comment] 2015-08-13 00:59
I repro'd this error, we'll take a look.  Thanks for the report.

What's your kb username btw?

**Comment by SyntaxPolice** [comment] 2015-08-13 04:18
Thanks. I'm ijones.

**Comment by oconnor663** [comment] 2015-08-13 16:02
I'm able to repro the warning but not the error. How did you get the error?

The warning is a side effect of having initially uploaded a key without your `@keybase.io` identity in it, but also having not made any signatures in your account yet. There's a bug that makes the warning persist even after you do upload a new version of the key with the right identity in it, but that bug will go away as soon as you make any signatures (like tracking or identity proofs), so I'm not too worried about it. As long as it doesn't cause actual errors...

**Comment by SyntaxPolice** [comment] 2015-08-13 16:51
I think the error was because I wrote "keybase push" without the --update flag, but I wasn't worried about that; I was just trying different thing to see if I always get the warning.

I did the twitter verification and indeed I've stopped getting the warning about not proving ownership of my key.

**Comment by oconnor663** [comment] 2015-08-13 17:47
Cool, thanks for the update. I'll keep this open while I check how easy it is to fix.

**Comment by oconnor663** [comment] 2015-08-13 21:34
Ok, I just pushed a fix, and it looks like everything's working for me.

**Closed by oconnor663** 2015-08-13 21:34 UTC

**Comment by SyntaxPolice** [comment] 2015-08-13 22:24
Thanks!
