### ISSUE TITLE
SSL Cert EXPIRED for https://api-0.core.keybaseapi.com

### ISSUE THREAD

**Issue by ScottYates** [keybase/keybase-issues#4120] opened 2022-03-25 19:28 UTC
Unable to send messages or access a lot of the mobile client pages.

It expired :  ‎Friday, ‎March ‎25, ‎2022 2:02:32 PM (CST)

**Comment by donatj** [comment] 2022-03-25 19:42
Same here

**Comment by mlevin5** [comment] 2022-03-25 19:42
same here! someone pls fix

**Comment by henderjon** [comment] 2022-03-25 19:44
same here

**Comment by hardoc** [comment] 2022-03-25 19:45
this is personally causing me huge financial loss , please fix

**Comment by sercankum-bc** [comment] 2022-03-25 19:53
Same here

**Comment by johnnysa2** [comment] 2022-03-25 19:55
Same here
(https://user-images.githubusercontent.com/102386550/160191518-1f3c4a18-ed6e-4dd8-98a4-f770609e97ef.png)


(The solution i'm found for now was edit windows clock to some hours ago)

**Comment by hardoc** [comment] 2022-03-25 20:02
is there any way to reproduce the clock trick @johnnysa2  please tell me immediately the timing is very bad for me and I was relying on keybase API for something pretty important , simply rewinding clock doesn't work for me

**Comment by hardoc** [comment] 2022-03-25 20:03
I'm closely monitoring this thread if anyone can help , let me know

**Comment by mikesoares** [comment] 2022-03-25 20:06
How do we further escalate this? I'm sure tons of us have files we need to get out.

**Comment by iriepariah** [comment] 2022-03-25 20:08
About 80% of the apps functions are not working.

**Comment by mikesoares** [comment] 2022-03-25 20:16
@songgao-zoom I see you ACK'ed this. Are you able to provide any updates?

**Comment by songgao-zoom** [comment] 2022-03-25 20:17
Hi all, sorry about the hiccup. We're investigating and trying to fix it. Will update here once it's fixed.

**Comment by songgao-zoom** [comment] 2022-03-25 20:19
Should be fixed now. Thanks all for your patience!

**Closed by songgao-zoom** 2022-03-25 20:19 UTC
Labels: acked

**Comment by hardoc** [comment] 2022-03-25 20:21
thank you so much

**Comment by ScottYates** [comment] 2022-03-25 20:21
Thank you!

**Comment by songgao-zoom** [comment] 2022-03-25 20:24
(Not fixed by me but I'll take it for the team!)

**Comment by henricook** [comment] 2022-05-04 09:16
@songgao-zoom It looks like this is happening again?
![image](https://user-images.githubusercontent.com/82004/166653949-7536f67b-6a90-45d0-b5cc-971d34d85ac3.png)

**Comment by henricook** [comment] 2022-05-04 09:38
Resolved. If anyone else gets to this point and seems similarly stuck my problem here was:

- My company uses a TLS intercepting proxy
- Keybase ships its own CA with its app instead of using one of the generally internet trusted CAs and when it sees a cert signed by the intercepting proxy it bails out

Fix if you're in the same situation is:

- Configure Keybase proxy settings and 'allow TLS interception' so that keybase looks at your wider system settings for what certs to trust.

**Comment by ahmedyounes** [comment] 2022-07-21 23:59
i still have the same issue
