### ISSUE TITLE
Coinbase broke

### ISSUE THREAD

**Issue by gregtampa** [keybase/keybase-issues#1659] opened 2015-07-07 01:04 UTC
sent me an email below...which is cause of cpinbase network broken today. Please certify facts before mass sending emails to users saying their stuff is broke when it's not...k.
Uh-oh, mobman, 
your previously-proven coinbase identity mobman just broke. We've been checking it repeatedly,
and it's not working from our perspective.

If you deleted a public proof, remember that proofs *must* stay public so anyone can trust you without 
trusting the Keybase.io server.

If your identity has changed, you should revoke or replace the proof on Keybase. If it is still correct, but you
accidentally deleted it, you can generate a new proof. Either way, here is a link to your profile:

https://keybase.io/mobman

Thanks! -Keybase

**Comment by h4ck3rm1k3** [comment] 2015-07-07 01:07
The problem is that coinbase does not allow for these long posts. I cannot add my proof back in.

**Comment by maxtaco** [comment] 2015-07-07 01:09
Guys, we had an outage earlier due to Coinbase/CloudFlare DNS issues, but it's fixed earlier.  Sorry about the false alarm.  No reason to fix your proofs.

**Comment by h4ck3rm1k3** [comment] 2015-07-07 01:18
I clicked on retry and now I cannot do that anymore. The pop up is failing. " ( coinbase.com popup)" goes to : https://www.coinbase.com/h4ck3rm1k3/public-key
```
Page not found :
Sorry we couldn't find what you were looking for.
```

Here is my new proof that I cannot post.
### Keybase proof

I hereby claim:

  * I am h4ck3rm1k3 on coinbase.
  * I am h4ck3rm1k3 on keybase.
  * I have a public key whose fingerprint is B9B7 C03C 1471 4781 3571  8EE3 CF4C 26A9 237D A5CF

To claim this, I am signing this object:

```json
{
    "body": {
        "key": {
            "fingerprint": "b9b7c03c1471478135718ee3cf4c26a9237da5cf",
            "host": "keybase.io",
            "key_id": "cf4c26a9237da5cf",
            "kid": "0101f3e86c54386c1f68e0703bfce4430b68c83d860990f68ff2041c76e3bffbe0880a",
            "uid": "f11be366176abeb5cd87b58a92ee4b19",
            "username": "h4ck3rm1k3"
        },
        "revoke": {
            "sig_ids": [
                "aaae433453438010b5e9116a74ec995b02eb41bf4f46780e91674bded54525600f"
            ]
        },
        "service": {
            "name": "coinbase",
            "username": "h4ck3rm1k3"
        },
        "type": "web_service_binding",
        "version": 1
    },
    "ctime": 1436231480,
    "expire_in": 157680000,
    "prev": "c31c7dcc4d06a6db30888c21f1b4ed53091df0d5ec13a4be340197328ffc22b2",
    "seqno": 12,
    "tag": "signature"
}
```

with the key B9B7 C03C 1471 4781 3571  8EE3 CF4C 26A9 237D A5CF, yielding the signature:

```
-----BEGIN PGP MESSAGE-----
Version: GnuPG v1

owF9UltIFUEYPkfN1LCE3iqCRsqsY8zszM7uHpPudKGMirALctiZndX14J5z9qgp
erpYPRgRVlCUEEUUXbCQUCvIoiLpgkYP3XwISewm9dCLkUWzYm/RMMww///93//N
N9Oamx5IC/avn3c5P3WhP/j0EwtsbSsoaQQsZjWAcCOIivHNdtwK4cU9x60BYcAM
pnGIOSKanDrCqoZ0ITC3CVeoaShYs0yV2yAEKmNJv0LSMDMpFjkxGZOHiGPJ6D/w
0fEERBDZWOiUqwTLFdlUF1CDmNlcEIIhozrXsaVTaBhQJm1bgQRxjQoJsZmAug5N
SVc7TmcjxASmFGnUZIKp3NI1puqysRCEIcMHJoXnmtVCoisJj2KvGkUxSIWAJ+pi
UeF7kHQqpOwkCO8EpmkKgjFRsZQnxTJVGAhRUyOCG4bKoCIYQcwmNqGaDmWSaoRZ
wlKJqqgUQhuUS27Zs87h4+QTvXnMcX2j/qeopiHuB3cJFpkgiDDHteQLyao64SWd
mAvCSCJ5jePXI4KpghHRYQiI+rjjiYjjI1SN6lCOEIjLW/rdMSrnmsU5sSA1qcWw
9FHnCrIRI1I8hgaybGipgiNsEukpgcjQsCL954rCFODfKeHGJLkihZoVklTa5po1
tZ4AqZyW4KyMQDAtkDkpzf9mgZzsvL9/7/2NrEBzRWfxs1f3t9z1lmhTDgTPeCdd
9vDe8vamnJKG74tFVzBxxe3teHIuO2tTYs/59z0lk/eXNxacPFam/FBXpW56eW07
lETfmpLC1WPfsvriyfS5w6eu0+KFh7dfODu9qZs8b383tPZm86PTp379tpGBZqzo
ajqRsTEzPP/E0ODRvLK8zQPVt/LH1i29NrBveOpg7oP2WcvuH0xWrcBtn+d0JUZb
WmeOdmdniFF9LNa7+86H2Rt6G1+ntb7bNlI4fKR+u7IAv/1YdPvYYH7n41TBjtz6
0mWTv1w8MnLuamEPnDZQV7U+lHOp6FDg55Lml3tXvijtPz5y9MHX4jdnZ0ZGOz6R
lu9/AA==
=+QAk
-----END PGP MESSAGE-----

```

And finally, I am proving ownership of the coinbase account by posting this on coinbase.com

### My publicly-auditable identity:

https://keybase.io/h4ck3rm1k3

```

**Comment by maxtaco** [comment] 2015-07-07 01:19
@malgorithms might need to take a look if the U/I is broken

**Comment by anfedorov** [comment] 2015-07-07 03:38
I don't remember what the place to paste the proof was before, but the only place I see to put something on my payment page is the caption, which is limited to 200 chars:

![screen shot 2015-07-06 at 11 38 44 pm](https://cloud.githubusercontent.com/assets/9820/8538270/2b2dfc44-2438-11e5-92f0-5960f8ceaab9.png)

**Comment by h4ck3rm1k3** [comment] 2015-07-07 03:40
@anfedorov exactly my problem. It is broken.

**Comment by gregtampa** [comment] 2015-07-07 09:13
Well my bug is on that the system wide email was sent out to all coinbase users because coinbase web servers was down due to an outage. Things such as this should be checked prior.
solved by running a subcheck of a query to the Api outside of a user to test connectivity before placing the error on the users account.

The ui field 200 characters limitation is just a JavaScript check which can be bypassed with inspect element so not a bug since you can hack it ...

**Comment by anfedorov** [comment] 2015-07-07 11:57
On Tue, Jul 7, 2015 at 5:13 AM, Gregory Hanis <notifications@github.com>
wrote:

> The ui field 200 characters limitation is just a JavaScript check which
> can be bypassed with inspect element so not a bug since you can hack it ...


Yeah, that doesn't seem legal.

200 characters seems like it should be enough to fit a simpler proof. Can
we get a shorter version of the claims that keybase will accept?

**Comment by h4ck3rm1k3** [comment] 2015-07-07 12:04
@gregtampa I could not find the line to change in the java script quickly. I am just trying to help here, I dont need this and will just leave it if you dont consider the 404 a bug in the integration. I cannot seem to find a place to report a bug to coin base either.

**Comment by anfedorov** [comment] 2015-07-07 12:07
Coinbase does bug reports via hackerone: https://hackerone.com/coinbase

**Comment by h4ck3rm1k3** [comment] 2015-07-07 12:17
@anfedorov thanks. https://hackerone.com/reports/74285

**Comment by malgorithms** [comment] 2015-07-07 13:21
it seems there are a couple separate issues being discussed here:

1. the Coinbase network problem yesterday, which is what this issue was posted about. (This is fixed.)
2. the question of where to post the proof...

Once your payment page is activated on Coinbase, you should go to 

https://www.coinbase.com/{yourcoinbasename}/public-key

to change your Keybase proof. This is linked to when first going through the proof, but is there a place we should be linking to it again on Keybase?  If so, let me know.  

(Your proof doesn't go in your payment page caption field, which is where the 200 character limit is.)

**Comment by h4ck3rm1k3** [comment] 2015-07-07 13:22
as I wrote before this public-key page is 404:

```
I clicked on retry and now I cannot do that anymore. The pop up is failing. " ( coinbase.com popup)" goes to : https://www.coinbase.com/h4ck3rm1k3/public-key

Page not found :
Sorry we couldn't find what you were looking for.

```

**Comment by malgorithms** [comment] 2015-07-07 13:36
ok, a 3rd issue, all compressed into one!

@h4ck3rm1k3 was your proof working before, and it stopped working yesterday during the Coinbase outage? 

I ask because it appears you haven't got a payments page at all (this is a Coinbase thing). We mention it in the instructions:

![image](https://cloud.githubusercontent.com/assets/614943/8547091/81244778-248a-11e5-8840-0c1a4eead827.png)

This page should load for you, otherwise you can't do a Keybase proof:

https://www.coinbase.com/h4ck3rm1k3

It should look something like this:

https://www.coinbase.com/bitcoyne

Once your payments page is working, then the popup we send you to for hosting a statement on Coinbase should work.

I'd like to get Coinbase to make a small change that would make this easier but it's not code I control.

**Comment by h4ck3rm1k3** [comment] 2015-07-07 13:39
@malgorithms thanks, it looks like I am being silly. https://www.coinbase.com/jdupont is my page not https://www.coinbase.com/h4ck3rm1k3 ! sorry for the false alarm.

**Comment by malgorithms** [comment] 2015-07-07 13:42
ok, cool! 

I'm emailing someone at Coinbase right now hoping to find a way to streamline this. It's very confusing, I think...and we need to get pretty creative.

**Comment by gregtampa** [comment] 2015-07-07 15:17
Mal not limited to just coinbase more of mass email sent to users when a service outage. Should be verified before wasted resources

**Comment by anfedorov** [comment] 2015-07-07 15:25
Got it. Is the /public-key link somewhere in the process that I missed, or
are people just supposed to know that?

**Comment by malgorithms** [comment] 2015-07-07 15:39
@anfedorov - it depends, did you start the process from the website? If so, look at the screenshot I posted above. We link through to the process of turning on your payments page at the beginning. If you're in the CLI the whole time, I'm not sure. But we'll be cleaning that up soon in the Go client.

Soon we're going to change it so you can't get past step 1 (entering your coinbase name) without having an active payment page. the client will have keybase server check to make sure the payment page is live, and if not, we'll alert you very aggressively that you have to turn it on.

as for the specific link to the public-key page that's in the final step:

![image](https://cloud.githubusercontent.com/assets/614943/8550120/9a163892-249c-11e5-883a-69e88fb4cd9f.png)

that link is straight to your /public-key page but it's the page that 404's if you don't have payment page turned on.

**Comment by anfedorov** [comment] 2015-07-07 16:34
I missed that, seems nearly perfect. Making two clear points there (1)
enable payment page, (2) paste public key. Might be nice, as even after
doing it I totally forgot that there were two steps, and the coinbase site
doesn't link the public key page anywhere.

Checking for an active payment page will work too, of course. Thanks for
the quick responses!

**Comment by feoh** [comment] 2015-09-11 14:28
I can't make the Coinbase proof work at all under any circumstances. Tried several times.  I also don't see a "Payments Page" setting in Coinbase, but I *do* see a "Public page" which I defined, and that name is what I passed to Keybase.

**Comment by Xe** [comment] 2015-09-15 15:33
I'm running into this too.

**Comment by malgorithms** [comment] 2015-09-15 15:45
@feoh and @xe they changed their terminology slightly and we'll update the site. Is this where you set your name? (Screenshot of what I see:)

![image](https://cloud.githubusercontent.com/assets/614943/9881634/d2c98fe8-5b9e-11e5-878d-741667ee6d56.png)

And anyone can load my profile page at https://coinbase.com/bitcoyne - are your profile pages loadable to others?

So on Keybase I can enter *bitcoyne* as my username, and it works.

**Comment by feoh** [comment] 2015-09-15 15:48
@malgorithms Yes that's the screen I use.  Not sure about others seeing the page - mine's https://coinbase.com/feoh

**Comment by malgorithms** [comment] 2015-09-15 15:53
ok, yeah, that loads fine for me. 

What happens when you go to:

https://www.coinbase.com/feoh/public-key

(I think that's where the dialog window links to. let me know if not. )  does coinbase let you post the proof?

**Comment by feoh** [comment] 2015-09-15 16:22
@malgorithms Yep that link worked perfectly. I pasted in the text Keybase generated for me and had it verify the proof, which it did.  Thanks for the fix!

**Comment by malgorithms** [comment] 2015-09-15 17:05
@feoh cool - do you know, was the site giving you the wrong link before? Or just bad messaging on getting the public page live?

**Comment by feoh** [comment] 2015-09-15 17:30
@malgorithms Yup the link was wrong (and as a result) the instructions were unclear.  Not sure how much of a percentage of my confusion was one versus the other because you helped me to a solution :)

**Comment by zQueal** [comment] 2015-09-15 19:22
My Coinbase broke just the other day. For whatever reason they removed the public URL to my key. I had to re setup my profile to include my public key, and reauthor from Keybase. Seems to be working now.

**Comment by malgorithms** [comment] 2015-09-18 13:57
hi all - I just cleaned up the Coinbase experience with some more pleasant sanity checking and instructions at the beginning. I'm going to close this issue, but here's some screenshots of the experience now:

First you enter a username:
![image](https://cloud.githubusercontent.com/assets/614943/9960697/309c5aae-5dea-11e5-9f2e-d7a5a74ceca6.png)

If coinbase.com/username exists, then it proceeds as normal:

![image](https://cloud.githubusercontent.com/assets/614943/9960718/46f6ae44-5dea-11e5-92f3-6e72aafcc8b6.png)


But, if it doesn't exist (which will produce the 404 at the end) you're not allowed to proceed:

![image](https://cloud.githubusercontent.com/assets/614943/9960740/62e68156-5dea-11e5-8160-27f80d568dad.png)

of course you could be erroneously typing someone else's coinbase name (who happens to have a public URL) at that stage, and you won't be able to complete the proof at the end. But this kind of user error is true of all the proof types.

**Closed by malgorithms** 2015-09-18 13:57 UTC

**Comment by mikeatlas** [comment] 2015-09-22 22:14
Please consider re-opening, 200 character limit in the caption is broken. Coinbase Public URL is working fine (in fact, I don't personally see any private vs public setting in Coinbase for my personal URL, and you can fit the twitter or Hacker News version of the verification in the box. 

![screen shot 2015-09-22 at 6 07 02 pm](https://cloud.githubusercontent.com/assets/12704/10033054/fbdb5996-6154-11e5-9fc6-4ccbb9b56f7a.png)

Too long. Here's me attempting to save my HN version:

![screen shot 2015-09-22 at 6 08 03 pm](https://cloud.githubusercontent.com/assets/12704/10033059/0036d5d8-6155-11e5-9262-fe2284329c1b.png)

And you can [verify it yourself](https://www.coinbase.com/mikeatlas) that size fits, although it looks kinda ugly and maybe Coinbase's CSS attribute added (`word-wrap: break-word`) to make it look a little less ugly... maybe I'll open a ticket with them too.

![screen shot 2015-09-22 at 6 13 21 pm](https://cloud.githubusercontent.com/assets/12704/10033140/a606ae16-6155-11e5-9545-e26c4c475a31.png)

**Comment by malgorithms** [comment] 2015-09-24 19:23
hi Mike, that's not where you post it.

Once the proof is generated, it links to where to post it, which is a special page on coinbase. Mine, for example, is: https://www.coinbase.com/bitcoyne/public-key

yours is here:

https://www.coinbase.com/mikeatlas/public-key

this is what I see when I look at it:

![image](https://cloud.githubusercontent.com/assets/614943/10084182/1a626a04-62d0-11e5-8cc2-fc465319c59c.png)


see - there's a note that you haven't uploaded a public key - that's where you paste your KB proof.

**Comment by mikeatlas** [comment] 2015-09-24 20:48
@malgorithms you're right, though on first attempt my session seemed to either have reset on landing on that page (`/username/public-key1) either because I was slow and my session timed out, or because of the referral header maybe on arrival? I had to re-login to Coinbase before I could find the textbox to upload my public key:

![screen shot 2015-09-24 at 4 45 37 pm](https://cloud.githubusercontent.com/assets/12704/10086335/d9368630-62db-11e5-9ad7-d926a2526e29.png)

Seems to be working for me now. https://www.coinbase.com/mikeatlas/public-key 

Thanks for the extra instructions.
