### ISSUE TITLE
ERROR exec: "gpg": executable file not found in $PATH

### ISSUE THREAD

**Issue by reybango** [keybase/keybase-issues#1957] opened 2016-01-13 03:04 UTC
New user. I ran through all the described steps for installing Keybase on OSX via Homebrew. Then went about generating my key with "keybase pgp gen". The key looks to have been generated but at the end of the process I got the following:

ERROR exec: "gpg": executable file not found in $PATH

I don't have gpg installed so that makes sense but reading this post I'm wondering if this is a regression or my error for not having gpg installed:

https://www.bountysource.com/issues/8850174-gpg-is-required-for-daemon

Feedback?

**Comment by patrickxb** [comment] 2016-01-14 16:58
Hi, you do not need gpg installed.

This is a bug on our end.  We are incorrectly handling one "gpg not found" error and reporting it to users.  Will fix soon!

As you noticed, the key should have been generated just fine.  This is the last step in `keybase pgp gen` and your newly generated pgp key should be in perfect working order.

Thanks for the bug report!

**Comment by reybango** [comment] 2016-01-14 17:09
@patrickxb thanks for the reply! Glad to help.

**Comment by wkretzsch** [comment] 2016-01-25 09:01
Hi not sure if merge #1735 was supposed to fix this issue, but I am still encountering it with keybase version `1.0.7-0`.

**Comment by ehmorris** [comment] 2016-02-05 15:50
I also encountered the error while setting up, and while running `keybase pgp pull`

**Comment by oconnor663** [comment] 2016-02-09 22:30
@wkretzsch I think the issue was fixed in 1.0.8. Could you update and try again?

@ehmorris what version are you using? Could you describe the commands you're running, and which one prints the error?

**Comment by ehmorris** [comment] 2016-02-10 16:45
@oconnor663 `1.0.7-0` — I encountered the error running `keybase pgp gen` while setting up, and `keybase pgp pull` while going through the listed commands and trying them out.

**Comment by oconnor663** [comment] 2016-02-10 17:02
Ok, hopefully the more recent releases fix the issue for both of you.

**Comment by rudeworks** [comment] 2016-02-22 13:20
I just experienced this issue running ```keybase 1.0.13-0``` on Mac OS X 10.11.3 when running ```keybase pgp gen```. Let me know if logs or whatever may be helpful.

**Comment by oconnor663** [comment] 2016-02-23 15:24
@rudeworks could you please do a `keybase log send` and tell us the log ID it generates for you?

**Comment by oconnor663** [comment] 2016-02-23 17:30
Filing https://keybase.atlassian.net/browse/CORE-2604 internally. @patrickxb, any chance this regressed?

**Comment by rudeworks** [comment] 2016-02-23 17:41
@oconnor663 it generated this ID: ```4864bfce7276d57717849b1c```

**Comment by oconnor663** [comment] 2016-02-23 20:12
@rudeworks, looking through that log, I don't see anything from a `keybase pgp pull`. Instead it looks more like a `pgp select` or a `pgp pull`, which are expected not to work if you don't have GPG installed. Any chance that's what happened?

**Comment by rudeworks** [comment] 2016-02-24 08:24
@oconnor663 I just tried again and it worked perfectly, maybe a reboot helped?

**Comment by oconnor663** [comment] 2016-02-24 16:45
Interesting, I'll close for now.

@gabriel could this have been a failure to auto-restart the old running daemon after an upgrade? How does this work on OSX?

**Closed by oconnor663** 2016-02-24 16:45 UTC

**Comment by gtalarico** [comment] 2018-05-16 00:15
Hello - I installed keybase from the dmg download yesterday - this problem still exists:
<img width="447" alt="screen shot 2018-05-15 at 8 14 07 pm" src="https://user-images.githubusercontent.com/9513968/40089941-99965cf0-587c-11e8-9a10-77a8086dbdec.png">

**Comment by Crypt-ix** [comment] 2018-05-16 22:36
Yep, i'm having the same issue on Windows.

![image](https://user-images.githubusercontent.com/16103757/40147497-3901e030-59ad-11e8-9edb-5d028f0cbf3e.png)

**Comment by zanderz** [comment] 2018-05-16 22:44
@Crypt-ix What happens if you invoke `gpg` at that same command line, or `where gpg.exe` (or `gpg2` and `where gpg2.exe`)?

**Comment by iamaer4fa** [comment] 2021-06-02 05:49
The issue is still happening. I have existing PGP key so I need to keybase pgp select and that will result the error that "pgp executable file not found in %PATH"
