### ISSUE TITLE
OSX - White windows

### ISSUE THREAD

**Issue by astropanic** [keybase/keybase-issues#2588] opened 2016-09-24 22:04 UTC
After reinstalling the newest downloaded .dmg from the [release](https://prerelease.keybase.io/Keybase.dmg) link I got this:

![screen shot 2016-09-25 at 00 00 13](https://cloud.githubusercontent.com/assets/39388/18811537/4e647726-82b3-11e6-814d-8e61e7f83447.png)

El Capitan 10.11.6

Any suggestions ?

**Comment by maxtaco** [comment] 2016-09-26 13:30
Can you, from the command-line prompt, do a `keybase log send`?

Cc: @gabriel  and @cjb

**Comment by astropanic** [comment] 2016-09-26 17:54
done

my log id: abf483e6ac2c6ba49c0fcb1c

**Comment by gabriel** [comment] 2016-10-07 20:29
@chrisnojima found the issue and we have a fix and are testing

**Comment by gabriel** [comment] 2016-10-07 20:30
Closing here as dupe of https://github.com/keybase/client/issues/4472

You can subscribe to that issue for fix progress. Thanks for the bug report!

**Closed by gabriel** 2016-10-07 20:30 UTC
