### ISSUE TITLE
"Buddy" is unfoundedly gender-specific language 

### ISSUE THREAD

**Issue by fischman** [keybase/keybase-issues#1678] opened 2015-07-16 05:36 UTC
Upon password reset success I am called Buddy by the site, even though I never identified as male to it.

**Comment by pathawks** [comment] 2015-07-16 07:25
Is there a special term for a female buddy?

**Comment by neurovertex** [comment] 2015-07-16 09:45
https://en.wiktionary.org/wiki/buddy
http://www.oxforddictionaries.com/definition/english/buddy
http://english.stackexchange.com/a/148680

It seems buddy is widely considered not to be gender-specific (not anymore at least).

**Comment by zQueal** [comment] 2015-07-16 17:28
Are you trying to be less gender specific with this, or are you legitimately offended by it?

Buddy is pretty gender inspecific IMHO.

**Comment by fischman** [comment] 2015-07-16 19:41
@pathawks not that I know of, though I'm not sure why you ask this considering the site doesn't ask for gender, so it's not like it could use a gender-appropriate alternative here.

@neurovertex "buddy" has many interrelated meanings, among which there is varying gender-specificity, but IMO the meaning in which it is used in the message in question has a strong gender-specificity.

@zQueal I took no personal offense at the usage, though I was put off by it.  I reported the issue under the assumption that the site wants to maximize its appeal, and the opinion that the sentence as written implies an assumption that all users of the site are male.

FWIW s/buddy/friend/ in the message keeps the tone and drops the assumption and is what I would do.

**Comment by zQueal** [comment] 2015-07-16 23:12
> I reported the issue under the assumption that the site wants to maximize its appeal

I'm positive that's the case. 

> the opinion that the sentence as written implies an assumption that all users of the site are male.

Yea, sure. I can see where you're coming from there.

**Comment by roboman2444** [comment] 2015-07-26 02:31
I don't see how "buddy" is gender specific... Something like "bro" or "dude" would be worth changing.
If "buddy" is enough of an issue to get a user to stop using the site, maybe they shouldn't be using it in the first place.
I don't see how this is worth the time and effort of the person who submitted the issue, or the devs who have to deal with it.

**Comment by zQueal** [comment] 2015-07-26 04:13
> If "buddy" is enough of an issue to get a user to stop using the site, maybe they shouldn't be using it in the first place.

That's entirely the wrong outlook here. Losing a user, or more, over a single phrase is hardly worth it at all.

> I don't see how this is worth the time and effort of the person who submitted the issue, or the devs who have to deal with it.

Undoubtedly this isn't the case __at all__ but if someone believes that their time is too good to change a simple word from one to another at the behest of its users--then maybe they shouldn't be developing? We're living in a changing world. If for any reason the word "buddy" were to inflame the inner SJW of a Keybase user and it were to launch a smear campaign against Keybase for "ableist" (or whatever, I have no idea about SJW-ish stuff) speech then Keybase would be losing an untold number of members over a simple word choice and the inability to take about 15 seconds and switch around some plain text. That hardly seems worth it......

**Comment by CodingAnarchy** [comment] 2015-07-26 04:20
> Losing a user, or more, over a single phrase is hardly worth it at all.

While this is true, there is a point at which it becomes problematic and unhelpful to spend one's time dealing with non-issues - and a basic phrase of common parlance is truly a non-issue.  Sure, it doesn't matter to change it now, but there's always something to complain about for some people.  Just my two cents.

**Comment by zQueal** [comment] 2015-07-26 19:54
@CodingAnarchy While I totally respect your opinion--I'm not advocating for change, here. I'm simply playing devil's advocate and saying that taking the _literal_ __15 seconds__ to change a phrase isn't worth starting some SJW revolt against Keybase over. I mean these guys and gals aren't exactly known for being reasonable and logical. 

> and a basic phrase of common parlance is truly a non-issue

I'd have to say I disagree with that one statement. If its enough of an issue to garner discussion it's definitely an issue.... At least IMO.

**Comment by roboman2444** [comment] 2015-07-26 20:21
> Keybase would be losing an untold number of members over a simple word choice
If that was the case, then those members are probably not beneficial to the project in the first place, and the project didn't benefit them either.
On the flip side, you might have some users or active developers who get fed up with the drama caused by non-issues, and decide to leave as well.

**Comment by pathawks** [comment] 2015-07-26 21:13
>  isn't worth starting some SJW revolt against Keybase over. I mean these guys and gals aren't exactly known for being reasonable and logical.

Quite the strawman you’ve built there

**Comment by revmischa** [comment] 2015-08-26 02:56
The gender-neutral term is "smooth buddy"
![Smooth buddy](https://www.jerkcity.com/jerkcity968.gif)

**Comment by benwaffle** [comment] 2015-08-26 12:56
:+1:

**Comment by malgorithms** [comment] 2015-09-16 19:04
Closing this issue since I use the term "buddy" independent of gender, and I'll continue to do so.

Thanks for submitting, though, it's always worth reflecting on this kind of thing...

**Closed by malgorithms** 2015-09-16 19:04 UTC
