### ISSUE TITLE
CLI Issues on macOS

### ISSUE THREAD

**Issue by danielmcclure** [keybase/keybase-issues#2592] opened 2016-09-28 15:26 UTC
I installed the latest version for Mac via DMG and then attempted to use the CLI line but this was linked to previous install (pre kbfs), so I uninstalled that and then nothing registered when attempting to use the CLI. Next I uninstalled everything and reinstalled just the latest version but still no CLI. It has also thrown a couple errors and I've had to revoke the keys from first install? Any idea how I can get the new version working and where the broken links may be?

**Comment by maxtaco** [comment] 2016-09-28 15:45
Cc: @gabriel 

Which Terminal are you using?  Which shell are you using?  We're working around a new regression in Sierra here but clearly haven't hit all of the cases.

Likely `keybase` is installed in `/usr/local/bin`, but also like that directory isn't in your path...

**Comment by zacharyrs** [comment] 2016-10-02 01:37
I appear to have this issue too. I'm running Sierra, using hyperterm with zsh.

`/usr/local/bin` is in my path, but there is no `keybase` executable in there.

**Comment by davidcurrie** [comment] 2016-10-02 11:15
Same here. Installed Keybase app under Sierra. `keybase` is in `/Applications/Keybase.app/Contents/SharedSupport/bin/keybase` but it didn't end up anywhere on my path.

**Comment by zacharyrs** [comment] 2016-10-02 11:18
I ended up just symlinking it into `/usr/local/bin`, which appears to have worked fine. Not sure what caused the ordeal though.

**Comment by gabriel** [comment] 2016-10-04 00:57
The Sierra issue is fixed, https://github.com/keybase/client/issues/4398.

Also Keybase.app has to be installed to /Applications for symlink to be installed. This is a bummer and something we'll fix soon!

**Comment by gabriel** [comment] 2016-10-04 00:58
Closing as dupe of https://github.com/keybase/client/issues/4398 or https://github.com/keybase/client/issues/4151. Please subscribe to issues there.

**Closed by gabriel** 2016-10-04 00:58 UTC

**Comment by danielmcclure** [comment] 2016-10-04 01:13
Sorry I haven't been around post few days to comment. Just logged back on and latest update fixes the issue as described. Thanks everyone!
