### ISSUE TITLE
FIDO U2F Support

### ISSUE THREAD

**Issue by zQueal** [keybase/keybase-issues#1169] opened 2014-10-24 03:29 UTC
The FIDO alliance just released their FIDO U2F hardware token. I just picked one up and hooked it to my Google account. It's very simple to setup and seems to be very secure. [More info.](https://fidoalliance.org/)

I'd be very interested in seeing this for Keybase, and __any__ other form of 2FA support sometime relatively soon.

There is a downfall to the FIDO U2F--which is it __requires__ Google Chrome to work properly, but as the standard grows I'm sure support for other browsers will expand.

[Quick video.](http://vimeo.com/72978755)

**Comment by hkjn** [comment] 2016-01-12 13:55
This issue seems like it might be a (near-)dupe of #808?

**Closed** 2016-02-10 00:27 UTC
