### ISSUE TITLE
Unable to recover passphrase; fails with "ERROR EOF"

### ISSUE THREAD

**Issue by callumd789** [keybase/keybase-issues#2083] opened 2016-02-18 15:20 UTC
I've managed to forget my passphrase, and am attmepting to recover it from the command line.

This is what happens when a correct paper key is used:

```
callumd@donquixote:~$ keybase passphrase recover
Password recovery will put your account on probation for 5 days.
You won't be able to perform certain actions, like revoking devices.
Continue with password recovery? (type 'YES' to confirm): YES
▶ ERROR EOF
callumd@donquixote:~$ 
```

When an incorrect paper key is used:

```
callumd@donquixote:~$ keybase passphrase recover
▶ INFO Forking background server with pid=6064
Password recovery will put your account on probation for 5 days.
You won't be able to perform certain actions, like revoking devices.
Continue with password recovery? (type 'YES' to confirm): YES
▶ ERROR Invalid key version
callumd@donquixote:~$ 

```

version information:

```
callumd@donquixote:~$ keybase version
Client:  1.0.12-0
Service: 1.0.12-0
```

**Comment by maxtaco** [comment] 2016-02-18 15:27
Seems like your daemon crashed :( Can you do a `keybase log send`

**Comment by callumd789** [comment] 2016-02-18 15:30
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Hello Max,

I've done as requested. It generated a couple of errors:

▶ WARNING error opening log
"/home/callumd/.cache/keybase/keybase.kbfs.log": open
/home/callumd/.cache/keybase/keybase.kbfs.log: no such file or directory
▶ WARNING error opening log
"/home/callumd/.cache/keybase/Keybase.app.log": open
/home/callumd/.cache/keybase/Keybase.app.log: no such file or directory



The log ID is:  48956dfdd56764bde1693c1c

Here's a URL to submit new bug reports containing this ID:

c.d.

On 18/02/16 15:27, Maxwell Krohn wrote:
> Seems like your daemon crashed :( Can you do a |keybase log send|
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/keybase/keybase-issues/issues/2083#issuecomment-18
5774287>.
>
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJWxeOmAAoJEKDaLLM0zahGsXwQAIOqeE+OagTW6EbaVcuZRHUN
433c+clMcNBccQMjOlfKHwKPIU773zBq5QY4gn3H/Ew3Ezj8uIQDZ6Je+i7AkOkg
V5fi8cNGw01w4UawW6JDOfgilNY2cwnR5K2hyCUV+gk2s5L3tVt1Un+hieXyPdGk
iZUopWknf+4kDmLGT99Stt244B1ds8t5i6GUJFAUL7J2EmTbnshw2CK98rrLv9sX
txkz2ZTSIFdI7fFdy5H+sfSdZ1zHTD/OeM8p5L77T9bkDkLr1SUpZgHUXUoyEOYU
CYzLimAzvSfH70qu/WDFBVZrMfscAe2Gvojb6dAqURNOOLSpnHSbWw/Ol2xMiKtD
KiOUA45ioVLeKU2t5FC3OqzzAd+82ywKgsA48Qm60kxekj4wrKIJiWXZ3fVYuGAQ
J18Z5Coz3hFAQqBGd5Xes12upVMB6PFz52KhqTp0Y8Fv1G9DJzKkql7K2lKPh2ET
ZmJ+YCC9ApvA//uRzOdRQoyzEUFrc/US+0FQBYOeIuy43kUoeWBk1Murt6JL6dHg
PeE5/HlVFdwHEX2rHMJJqHA8UJFNUx94ZroL2eZZuNfFLJkka6OHJLFCjBNRYLxe
Vy86ofW4PNHt1cxsFVCLzD1YXba1OPS3F/fPMk6caNKLnOzJBvHTMIufqi3PwZyo
Mdw8MHWbUdvtMn5t/0bc
=KJ96
-----END PGP SIGNATURE-----

**Comment by maxtaco** [comment] 2016-02-18 15:42
Took a quick look, it looks quite solvable (phew!) we'll report back soon with more details.  Service dump is here:

```
goroutine 56 [running]:
7 github.com/keybase/client/go/libkb.(*SKB).lksUnlockWithSecretRetriever(0xc82009d3f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
8 /root/build_keybase/gopaths/amd64/src/github.com/keybase/client/go/libkb/skb.go:432 +0x63
9 github.com/keybase/client/go/libkb.(*SKB).unlockSecretKeyFromSecretRetriever(0xc82009d3f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
10 /root/build_keybase/gopaths/amd64/src/github.com/keybase/client/go/libkb/skb.go:264 +0x151
11 github.com/keybase/client/go/libkb.(*SKB).UnlockWithStoredSecret(0xc82009d3f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
12 /root/build_keybase/gopaths/amd64/src/github.com/keybase/client/go/libkb/skb.go:670 +0x16b
13 github.com/keybase/client/go/engine.(*PassphraseChange).findAndDecryptPrivatePGPKeys(0xc8203de1e0, 0xc8200f2750, 0x0, 0x0, 0x0, 0x0, 0x0)
14 /root/build_keybase/gopaths/amd64/src/github.com/keybase/client/go/engine/passphrase_change.go:413 +0x6ed
15 github.com/keybase/client/go/engine.(*PassphraseChange).updatePassphrase(0xc8203de1e0, 0xc8200f2750, 0x7f76985763b8, 0xc82044a000, 0x1, 0xc8204418c0, 0x20, 0x20, 0x0, 0x0)
16 /root/build_keybase/gopaths/amd64/src/github.com/keybase/client/go/engine/passphrase_change.go:168 +0x4a
17 github.com/keybase/client/go/engine.(*PassphraseChange).runForcedUpdate(0xc8203de1e0, 0xc8200f2750, 0x0, 0x0)
18 /root/build_keybase/gopaths/amd64/src/github.com/keybase/client/go/engine/passphrase_change.go:246 +0x2ce
19 github.com/keybase/client/go/engine.(*PassphraseChange).Run(0xc8203de1e0, 0xc8200f2750, 0x0, 0x0)
20 /root/build_keybase/gopaths/amd64/src/github.com/keybase/client/go/engine/passphrase_change.go:79 +0x289
21 github.com/keybase/client/go/engine.RunEngine(0x7f76980d02e0, 0xc8203de1e0, 0xc8200f2750, 0x0, 0x0)
22 /root/build_keybase/gopaths/amd64/src/github.com/keybase/client/go/engine/engine.go:78 +0x32b
23 github.com/keybase/client/go/service.(*AccountHandler).PassphraseChange(0xc8204440c0, 0x7f7699dbf538, 0xc820446340, 0x0, 0x0, 0x0, 0xc8204447e0, 0xc, 0x1, 0x0, ...)
24 /root/build_keybase/gopaths/amd64/src/github.com/keybase/client/go/service/account.go:32 +0x2da
25 github.com/keybase/client/go/protocol.AccountProtocol.func2(0x7f7699dbf538, 0xc820446340, 0xd7fca0, 0xc820468100, 0x0, 0x0, 0x0, 0x0)
26 /root/build_keybase/gopaths/amd64/src/github.com/keybase/client/go/protocol/keybase_v1.go:81 +0x18d
27 github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc.(*callRequest).Serve(0xc8203de180, 0x7f7699dbec10, 0xc820446840, 0xc8204681c0, 0x149f630)
28 /root/build_keybase/gopaths/amd64/src/github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc/request.go:76 +0x246
29 created by github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc.(*receiveHandler).handleReceiveDispatch
30 /root/build_keybase/gopaths/amd64/src/github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc/receiver.go:123 +0x3db
```

**Comment by maxtaco** [comment] 2016-02-19 20:40
We have a fix coming in v1.0.14. Thanks for this bug report!

**Comment by ardichoke** [comment] 2016-05-25 01:17
I'm now having this same issue on the latest version of keybase (v1.0.16)

Logs uploaded: 251f3fe11ae62a27280c341c

**Comment by maxtaco** [comment] 2016-05-25 01:23
I definitely see a crash, what happens if you `keybase logout` and `keybase login`?  I think it worked and crashed at the very end, though I'm not sure...

**Comment by ardichoke** [comment] 2016-05-25 01:25
This device is not currently, and never has been, logged into Keybase. I'm adding it for the first time. I'm using the recovery because, sadly, my other device that was actually added to Keybase suddenly doesn't think it's logged in for some inexplicable reason.

**Comment by maxtaco** [comment] 2016-05-25 01:27
Sorry about that login problem.  Last night's build is broken.  I'd wait for the next build.  CC: @cjb.  We're investigating the crasher too. Thanks!

**Comment by maxtaco** [comment] 2016-05-25 01:29
OK, I've confirmed no updates went through to the server.  I'd sit tight until tomorrow's release.  Or, in the mean time, in your working device, I believe it should work to logout and log back in.

**Comment by patrickxb** [comment] 2016-05-25 15:30
@ardichoke it looks like you built keybase from source with gcc go.  Could you try one of the official releases or build with regular go?  The stack trace at your panic is mangled and it's hard to determine where the nil pointer/invalid memory access happened.

**Comment by patrickxb** [comment] 2016-05-25 15:31
@ardichoke it looks like you built keybase from source with gcc go. Could you try one of the official releases or build with regular go? The stack trace at your panic is mangled and it's hard to determine where the nil pointer/invalid memory access happened.

**Comment by ardichoke** [comment] 2016-05-25 16:53
I didn't build keybase at all... I installed it from the Arch Linux repos.

**Comment by patrickxb** [comment] 2016-05-26 14:51
@ardichoke we're looking into it.  We believe there is an issue with arch linux using gccgo for keybase v1.0.16.  

cc @oconnor663

**Comment by Cysioland** [comment] 2016-05-26 20:38
Same happens with fresh login

**Comment by maxtaco** [comment] 2016-05-26 20:47
Also on arch?

**Comment by Cysioland** [comment] 2016-05-26 20:52
Well, considering, that Antergos is based on Arch, then yes.

**Comment by oconnor663** [comment] 2016-05-31 17:02
As far as I can tell, this is a bug in gcc-go. [This line] is a nil pointer assignment in gcc-go, but not in regular go. Here's a minimal reproducing case: https://play.golang.org/p/AKK9_LdyHs

**Comment by oconnor663** [comment] 2016-05-31 21:41
Possibly fixed in https://github.com/keybase/client/commit/ca023e2d6f9192fd8e923f3113ae4a11cda8b53a.

**Comment by Cysioland** [comment] 2016-05-31 22:04
@oconnor663 Fixed the thing for me

**Comment by oconnor663** [comment] 2016-05-31 22:39
@Cysioland awesome! How did you test? Manually editing the PKGBUILD?

**Comment by Cysioland** [comment] 2016-05-31 22:40
@oconnor663 Nope, `keybase-git` from AUR.

**Comment by felixonmars** [comment] 2016-06-01 02:46
Commit backported into [community]/keybase 1.0.16-2.

**Comment by oconnor663** [comment] 2016-06-01 14:26
@felixonmars thanks! @Cysioland it turns out `keybase-git` is built with the regular Go compiler instead of gcc-go, so we might not be able to call the fix verified yet. Could you try it with `community/keybase`?

**Comment by Cysioland** [comment] 2016-06-01 15:34
@oconnor663 `keybase logout` followed by `keybase login` on
`community/keybase` version works, though not sure, if actually that
step was broken, so can't really say it.

**Comment by Cysioland** [comment] 2016-06-01 15:37
@oconnor663 Actually I just deprovisioned my device and reprovisioned
it, and it worked like a charm

**Comment by oconnor663** [comment] 2016-06-01 16:37
Awesome, thanks.

**Closed by oconnor663** 2016-06-01 16:37 UTC
